name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'   # Trigger only when changes are made in the backend directory

jobs:
  build-and-deploy:
    runs-on: amazon-linux

    steps:
      # 1. Checkout Code
      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          path: demo-api

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # 3. Build Spring Boot Application
      - name: Build Spring Boot Application
        working-directory: ./demo
        run: |
          ./mvnw clean package

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build Docker Image
      - name: Build Backend Docker Image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-api:latest .

      # 6. Push Docker Image to Docker Hub
      - name: Push Backend Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-api:latest

      # 7. Deploy to EC2 via SSH
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest backend image
            docker pull ${{ secrets.DOCKER_USERNAME }}/demo-api:latest

            # Stop and remove existing backend container if it exists
            docker stop demo-api || true
            docker rm demo-api || true

            # Run the backend container
            docker run -d --name demo-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/demo-api:latest
